# Generated by Django 5.0.6 on 2024-11-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
